// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calendar_name`, `category_name`, `country_name`, `currency_name`, `language_name`, `parse_amount`, `parse_calendar`, `parse_category`, `parse_country`, `parse_currency`, `parse_date`, `parse_language`, `parse_planned_kind`, `parse_week_start`, `planned_kind_name`, `planned_status_name`, `report_snapshot`, `snapshot`, `week_start_number`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PouchApp>>
abstract class PouchApp implements RustOpaqueInterface {
  Future<AppSnapshot> addPurchase({
    required String id,
    required String date,
    required String description,
    required String amount,
    required String category,
  });

  Future<BudgetSnapshot> budgetSummary({required String date});

  Future<String> calendarDate({
    required int year,
    required int month,
    required int day,
    required String calendar,
  });

  Future<CalendarMonthSnapshot> calendarMonth({
    required String date,
    required String calendar,
    required int monthOffset,
  });

  Future<DatePartsSnapshot> dateParts({
    required String date,
    required String calendar,
  });

  Future<AppSnapshot> editPurchase({
    required String date,
    required String id,
    required String description,
    required String amount,
    required String category,
  });

  Future<String> exportBackup();

  Future<String> exportRecoveryBackup();

  Future<List<GoalForecastSnapshot>> goalForecast({required String asOf});

  Future<AppSnapshot> importBackup({required String contents});

  Future<AppSnapshot> markExpectedIncomeReceived({
    required String id,
    required String receivedDate,
  });

  Future<AppSnapshot> markPlannedPaid({
    required String planId,
    required String purchaseId,
    required String paidDate,
    required String amount,
  });

  static Future<PouchApp> open({
    required String applicationDataDirectory,
    required List<String> legacyJsonCandidates,
  }) => RustLib.instance.api.crateApiPouchAppOpen(
    applicationDataDirectory: applicationDataDirectory,
    legacyJsonCandidates: legacyJsonCandidates,
  );

  Future<AppSnapshot> recordIncome({
    required String id,
    required String date,
    required String amount,
  });

  Future<AppSnapshot> removeBudgetPlan({required String effective});

  Future<AppSnapshot> removeExpectedIncome({required String id});

  Future<AppSnapshot> removeIncome({required String id});

  Future<AppSnapshot> removePlanned({required String id});

  Future<AppSnapshot> removePurchase({
    required String date,
    required String id,
  });

  Future<ReportSnapshot> reportMonth({
    required String anchor,
    required String calendar,
  });

  Future<ReportSnapshot> reportRange({
    required String from,
    required String through,
  });

  Future<ReportSnapshot> reportSpecific({required List<String> days});

  Future<ReportSnapshot> reportWeek({
    required String anchor,
    required int weekStart,
  });

  Future<AppSnapshot> reset();

  Future<AppSnapshot> saveBudgetPlan({
    required String effective,
    String? salary,
    required String dailyBudget,
    required List<String> expenseIds,
    required List<String> expenseNames,
    required List<String> expenseAmounts,
    required String savings,
    required int payday,
  });

  Future<AppSnapshot> savePlanned({
    required String id,
    required String description,
    required String amount,
    required String category,
    required String kind,
    required String date,
  });

  Future<AppSnapshot> scheduleIncome({
    required String id,
    required String date,
    required String amount,
  });

  Future<AppSnapshot> setDailyOverride({required String date, String? amount});

  Future<AppSnapshot> snapshot();

  Future<String> today();

  Future<AppSnapshot> undoLastChange();

  Future<AppSnapshot> updateExpectedIncome({
    required String id,
    required String date,
    required String amount,
  });

  Future<AppSnapshot> updateIncome({
    required String id,
    required String date,
    required String amount,
  });

  Future<AppSnapshot> updatePreferences({
    required String country,
    required String currency,
    required String language,
    required String calendar,
    required int weekStart,
  });
}

class AppSnapshot {
  final int revision;
  final bool recovered;
  final bool imported;
  final String startDate;
  final PreferencesSnapshot preferences;
  final List<IncomeSnapshot> income;
  final List<ExpectedIncomeSnapshot> expectedIncome;
  final List<BudgetPlanSnapshot> plans;
  final List<DaySnapshot> days;
  final List<PlannedSnapshot> planned;

  const AppSnapshot({
    required this.revision,
    required this.recovered,
    required this.imported,
    required this.startDate,
    required this.preferences,
    required this.income,
    required this.expectedIncome,
    required this.plans,
    required this.days,
    required this.planned,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      recovered.hashCode ^
      imported.hashCode ^
      startDate.hashCode ^
      preferences.hashCode ^
      income.hashCode ^
      expectedIncome.hashCode ^
      plans.hashCode ^
      days.hashCode ^
      planned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          recovered == other.recovered &&
          imported == other.imported &&
          startDate == other.startDate &&
          preferences == other.preferences &&
          income == other.income &&
          expectedIncome == other.expectedIncome &&
          plans == other.plans &&
          days == other.days &&
          planned == other.planned;
}

class BudgetPlanSnapshot {
  final String effective;
  final int? salary;
  final int dailyBudget;
  final List<RequiredExpenseSnapshot> expenses;
  final int savings;
  final int payday;
  final String calendar;
  final bool legacy;

  const BudgetPlanSnapshot({
    required this.effective,
    this.salary,
    required this.dailyBudget,
    required this.expenses,
    required this.savings,
    required this.payday,
    required this.calendar,
    required this.legacy,
  });

  @override
  int get hashCode =>
      effective.hashCode ^
      salary.hashCode ^
      dailyBudget.hashCode ^
      expenses.hashCode ^
      savings.hashCode ^
      payday.hashCode ^
      calendar.hashCode ^
      legacy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BudgetPlanSnapshot &&
          runtimeType == other.runtimeType &&
          effective == other.effective &&
          salary == other.salary &&
          dailyBudget == other.dailyBudget &&
          expenses == other.expenses &&
          savings == other.savings &&
          payday == other.payday &&
          calendar == other.calendar &&
          legacy == other.legacy;
}

class BudgetSnapshot {
  final String date;
  final String periodEnd;
  final int daysRemaining;
  final int carry;
  final int daily;
  final int spent;
  final int remaining;
  final int income;
  final int requiredExpenses;
  final int savings;
  final int funds;
  final int reserved;
  final int recommendation;
  final int shortfall;

  const BudgetSnapshot({
    required this.date,
    required this.periodEnd,
    required this.daysRemaining,
    required this.carry,
    required this.daily,
    required this.spent,
    required this.remaining,
    required this.income,
    required this.requiredExpenses,
    required this.savings,
    required this.funds,
    required this.reserved,
    required this.recommendation,
    required this.shortfall,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      periodEnd.hashCode ^
      daysRemaining.hashCode ^
      carry.hashCode ^
      daily.hashCode ^
      spent.hashCode ^
      remaining.hashCode ^
      income.hashCode ^
      requiredExpenses.hashCode ^
      savings.hashCode ^
      funds.hashCode ^
      reserved.hashCode ^
      recommendation.hashCode ^
      shortfall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BudgetSnapshot &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          periodEnd == other.periodEnd &&
          daysRemaining == other.daysRemaining &&
          carry == other.carry &&
          daily == other.daily &&
          spent == other.spent &&
          remaining == other.remaining &&
          income == other.income &&
          requiredExpenses == other.requiredExpenses &&
          savings == other.savings &&
          funds == other.funds &&
          reserved == other.reserved &&
          recommendation == other.recommendation &&
          shortfall == other.shortfall;
}

class CalendarMonthSnapshot {
  final String startDate;
  final int year;
  final int month;
  final int dayCount;
  final int firstWeekday;

  const CalendarMonthSnapshot({
    required this.startDate,
    required this.year,
    required this.month,
    required this.dayCount,
    required this.firstWeekday,
  });

  @override
  int get hashCode =>
      startDate.hashCode ^
      year.hashCode ^
      month.hashCode ^
      dayCount.hashCode ^
      firstWeekday.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarMonthSnapshot &&
          runtimeType == other.runtimeType &&
          startDate == other.startDate &&
          year == other.year &&
          month == other.month &&
          dayCount == other.dayCount &&
          firstWeekday == other.firstWeekday;
}

class CategoryTotalSnapshot {
  final String category;
  final int amount;

  const CategoryTotalSnapshot({required this.category, required this.amount});

  @override
  int get hashCode => category.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryTotalSnapshot &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          amount == other.amount;
}

class DailyTotalSnapshot {
  final String date;
  final int amount;

  const DailyTotalSnapshot({required this.date, required this.amount});

  @override
  int get hashCode => date.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyTotalSnapshot &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          amount == other.amount;
}

class DatePartsSnapshot {
  final int year;
  final int month;
  final int day;

  const DatePartsSnapshot({
    required this.year,
    required this.month,
    required this.day,
  });

  @override
  int get hashCode => year.hashCode ^ month.hashCode ^ day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DatePartsSnapshot &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          month == other.month &&
          day == other.day;
}

class DaySnapshot {
  final String date;
  final int? budget;
  final List<PurchaseSnapshot> purchases;

  const DaySnapshot({required this.date, this.budget, required this.purchases});

  @override
  int get hashCode => date.hashCode ^ budget.hashCode ^ purchases.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DaySnapshot &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          budget == other.budget &&
          purchases == other.purchases;
}

class ExpectedIncomeSnapshot {
  final String id;
  final String date;
  final int amount;

  const ExpectedIncomeSnapshot({
    required this.id,
    required this.date,
    required this.amount,
  });

  @override
  int get hashCode => id.hashCode ^ date.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpectedIncomeSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          amount == other.amount;
}

class GoalForecastSnapshot {
  final String id;
  final int periods;
  final int? requiredMonthly;
  final int projected;
  final int percent;
  final int? difference;
  final bool onTrack;
  final int? completionDays;
  final int dailyReduction;

  const GoalForecastSnapshot({
    required this.id,
    required this.periods,
    this.requiredMonthly,
    required this.projected,
    required this.percent,
    this.difference,
    required this.onTrack,
    this.completionDays,
    required this.dailyReduction,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      periods.hashCode ^
      requiredMonthly.hashCode ^
      projected.hashCode ^
      percent.hashCode ^
      difference.hashCode ^
      onTrack.hashCode ^
      completionDays.hashCode ^
      dailyReduction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GoalForecastSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          periods == other.periods &&
          requiredMonthly == other.requiredMonthly &&
          projected == other.projected &&
          percent == other.percent &&
          difference == other.difference &&
          onTrack == other.onTrack &&
          completionDays == other.completionDays &&
          dailyReduction == other.dailyReduction;
}

class IncomeSnapshot {
  final String id;
  final String date;
  final int amount;

  const IncomeSnapshot({
    required this.id,
    required this.date,
    required this.amount,
  });

  @override
  int get hashCode => id.hashCode ^ date.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IncomeSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          amount == other.amount;
}

class PlannedReportSnapshot {
  final String date;
  final String id;
  final String description;
  final int amount;
  final String category;

  const PlannedReportSnapshot({
    required this.date,
    required this.id,
    required this.description,
    required this.amount,
    required this.category,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      id.hashCode ^
      description.hashCode ^
      amount.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlannedReportSnapshot &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          id == other.id &&
          description == other.description &&
          amount == other.amount &&
          category == other.category;
}

class PlannedSnapshot {
  final String id;
  final String description;
  final int amount;
  final String category;
  final String kind;
  final String date;
  final String status;
  final String? paidDate;
  final String? purchaseId;

  const PlannedSnapshot({
    required this.id,
    required this.description,
    required this.amount,
    required this.category,
    required this.kind,
    required this.date,
    required this.status,
    this.paidDate,
    this.purchaseId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      description.hashCode ^
      amount.hashCode ^
      category.hashCode ^
      kind.hashCode ^
      date.hashCode ^
      status.hashCode ^
      paidDate.hashCode ^
      purchaseId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlannedSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          description == other.description &&
          amount == other.amount &&
          category == other.category &&
          kind == other.kind &&
          date == other.date &&
          status == other.status &&
          paidDate == other.paidDate &&
          purchaseId == other.purchaseId;
}

class PreferencesSnapshot {
  final String country;
  final String currency;
  final String language;
  final String calendar;
  final int weekStart;

  const PreferencesSnapshot({
    required this.country,
    required this.currency,
    required this.language,
    required this.calendar,
    required this.weekStart,
  });

  @override
  int get hashCode =>
      country.hashCode ^
      currency.hashCode ^
      language.hashCode ^
      calendar.hashCode ^
      weekStart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreferencesSnapshot &&
          runtimeType == other.runtimeType &&
          country == other.country &&
          currency == other.currency &&
          language == other.language &&
          calendar == other.calendar &&
          weekStart == other.weekStart;
}

class PurchaseSnapshot {
  final String id;
  final String description;
  final int amount;
  final String category;
  final bool fundedByGoal;

  const PurchaseSnapshot({
    required this.id,
    required this.description,
    required this.amount,
    required this.category,
    required this.fundedByGoal,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      description.hashCode ^
      amount.hashCode ^
      category.hashCode ^
      fundedByGoal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PurchaseSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          description == other.description &&
          amount == other.amount &&
          category == other.category &&
          fundedByGoal == other.fundedByGoal;
}

class ReportEntrySnapshot {
  final String date;
  final String id;
  final String description;
  final int amount;
  final String category;
  final bool fundedByGoal;

  const ReportEntrySnapshot({
    required this.date,
    required this.id,
    required this.description,
    required this.amount,
    required this.category,
    required this.fundedByGoal,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      id.hashCode ^
      description.hashCode ^
      amount.hashCode ^
      category.hashCode ^
      fundedByGoal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReportEntrySnapshot &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          id == other.id &&
          description == other.description &&
          amount == other.amount &&
          category == other.category &&
          fundedByGoal == other.fundedByGoal;
}

class ReportSnapshot {
  final List<String> dates;
  final List<ReportEntrySnapshot> entries;
  final List<DailyTotalSnapshot> daily;
  final List<CategoryTotalSnapshot> categories;
  final List<PlannedReportSnapshot> planned;
  final int total;
  final int reserved;

  const ReportSnapshot({
    required this.dates,
    required this.entries,
    required this.daily,
    required this.categories,
    required this.planned,
    required this.total,
    required this.reserved,
  });

  @override
  int get hashCode =>
      dates.hashCode ^
      entries.hashCode ^
      daily.hashCode ^
      categories.hashCode ^
      planned.hashCode ^
      total.hashCode ^
      reserved.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReportSnapshot &&
          runtimeType == other.runtimeType &&
          dates == other.dates &&
          entries == other.entries &&
          daily == other.daily &&
          categories == other.categories &&
          planned == other.planned &&
          total == other.total &&
          reserved == other.reserved;
}

class RequiredExpenseSnapshot {
  final String id;
  final String name;
  final int amount;

  const RequiredExpenseSnapshot({
    required this.id,
    required this.name,
    required this.amount,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequiredExpenseSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          amount == other.amount;
}
