// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PouchAppPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchAppPtr;

  @protected
  PouchApp
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    dynamic raw,
  );

  @protected
  PouchApp
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    dynamic raw,
  );

  @protected
  PouchApp
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  PouchApp
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSnapshot dco_decode_app_snapshot(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BudgetPlanSnapshot dco_decode_budget_plan_snapshot(dynamic raw);

  @protected
  BudgetSnapshot dco_decode_budget_snapshot(dynamic raw);

  @protected
  CalendarMonthSnapshot dco_decode_calendar_month_snapshot(dynamic raw);

  @protected
  CategoryTotalSnapshot dco_decode_category_total_snapshot(dynamic raw);

  @protected
  DailyTotalSnapshot dco_decode_daily_total_snapshot(dynamic raw);

  @protected
  DatePartsSnapshot dco_decode_date_parts_snapshot(dynamic raw);

  @protected
  DaySnapshot dco_decode_day_snapshot(dynamic raw);

  @protected
  ExpectedIncomeSnapshot dco_decode_expected_income_snapshot(dynamic raw);

  @protected
  GoalForecastSnapshot dco_decode_goal_forecast_snapshot(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IncomeSnapshot dco_decode_income_snapshot(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BudgetPlanSnapshot> dco_decode_list_budget_plan_snapshot(dynamic raw);

  @protected
  List<CategoryTotalSnapshot> dco_decode_list_category_total_snapshot(
    dynamic raw,
  );

  @protected
  List<DailyTotalSnapshot> dco_decode_list_daily_total_snapshot(dynamic raw);

  @protected
  List<DaySnapshot> dco_decode_list_day_snapshot(dynamic raw);

  @protected
  List<ExpectedIncomeSnapshot> dco_decode_list_expected_income_snapshot(
    dynamic raw,
  );

  @protected
  List<GoalForecastSnapshot> dco_decode_list_goal_forecast_snapshot(
    dynamic raw,
  );

  @protected
  List<IncomeSnapshot> dco_decode_list_income_snapshot(dynamic raw);

  @protected
  List<PlannedReportSnapshot> dco_decode_list_planned_report_snapshot(
    dynamic raw,
  );

  @protected
  List<PlannedSnapshot> dco_decode_list_planned_snapshot(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PurchaseSnapshot> dco_decode_list_purchase_snapshot(dynamic raw);

  @protected
  List<ReportEntrySnapshot> dco_decode_list_report_entry_snapshot(dynamic raw);

  @protected
  List<RequiredExpenseSnapshot> dco_decode_list_required_expense_snapshot(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlannedReportSnapshot dco_decode_planned_report_snapshot(dynamic raw);

  @protected
  PlannedSnapshot dco_decode_planned_snapshot(dynamic raw);

  @protected
  PreferencesSnapshot dco_decode_preferences_snapshot(dynamic raw);

  @protected
  PurchaseSnapshot dco_decode_purchase_snapshot(dynamic raw);

  @protected
  ReportEntrySnapshot dco_decode_report_entry_snapshot(dynamic raw);

  @protected
  ReportSnapshot dco_decode_report_snapshot(dynamic raw);

  @protected
  RequiredExpenseSnapshot dco_decode_required_expense_snapshot(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  PouchApp
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    SseDeserializer deserializer,
  );

  @protected
  PouchApp
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    SseDeserializer deserializer,
  );

  @protected
  PouchApp
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  PouchApp
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSnapshot sse_decode_app_snapshot(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BudgetPlanSnapshot sse_decode_budget_plan_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BudgetSnapshot sse_decode_budget_snapshot(SseDeserializer deserializer);

  @protected
  CalendarMonthSnapshot sse_decode_calendar_month_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  CategoryTotalSnapshot sse_decode_category_total_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  DailyTotalSnapshot sse_decode_daily_total_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  DatePartsSnapshot sse_decode_date_parts_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  DaySnapshot sse_decode_day_snapshot(SseDeserializer deserializer);

  @protected
  ExpectedIncomeSnapshot sse_decode_expected_income_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  GoalForecastSnapshot sse_decode_goal_forecast_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IncomeSnapshot sse_decode_income_snapshot(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BudgetPlanSnapshot> sse_decode_list_budget_plan_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<CategoryTotalSnapshot> sse_decode_list_category_total_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<DailyTotalSnapshot> sse_decode_list_daily_total_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<DaySnapshot> sse_decode_list_day_snapshot(SseDeserializer deserializer);

  @protected
  List<ExpectedIncomeSnapshot> sse_decode_list_expected_income_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<GoalForecastSnapshot> sse_decode_list_goal_forecast_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<IncomeSnapshot> sse_decode_list_income_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<PlannedReportSnapshot> sse_decode_list_planned_report_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<PlannedSnapshot> sse_decode_list_planned_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PurchaseSnapshot> sse_decode_list_purchase_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<ReportEntrySnapshot> sse_decode_list_report_entry_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<RequiredExpenseSnapshot> sse_decode_list_required_expense_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlannedReportSnapshot sse_decode_planned_report_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  PlannedSnapshot sse_decode_planned_snapshot(SseDeserializer deserializer);

  @protected
  PreferencesSnapshot sse_decode_preferences_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  PurchaseSnapshot sse_decode_purchase_snapshot(SseDeserializer deserializer);

  @protected
  ReportEntrySnapshot sse_decode_report_entry_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  ReportSnapshot sse_decode_report_snapshot(SseDeserializer deserializer);

  @protected
  RequiredExpenseSnapshot sse_decode_required_expense_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    PouchApp self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    PouchApp self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    PouchApp self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    PouchApp self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_snapshot(AppSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_budget_plan_snapshot(
    BudgetPlanSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_budget_snapshot(
    BudgetSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_month_snapshot(
    CalendarMonthSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_category_total_snapshot(
    CategoryTotalSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_daily_total_snapshot(
    DailyTotalSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_date_parts_snapshot(
    DatePartsSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_day_snapshot(DaySnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_expected_income_snapshot(
    ExpectedIncomeSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_goal_forecast_snapshot(
    GoalForecastSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_income_snapshot(
    IncomeSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_budget_plan_snapshot(
    List<BudgetPlanSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_category_total_snapshot(
    List<CategoryTotalSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_daily_total_snapshot(
    List<DailyTotalSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_day_snapshot(
    List<DaySnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_expected_income_snapshot(
    List<ExpectedIncomeSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_goal_forecast_snapshot(
    List<GoalForecastSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_income_snapshot(
    List<IncomeSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_planned_report_snapshot(
    List<PlannedReportSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_planned_snapshot(
    List<PlannedSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_purchase_snapshot(
    List<PurchaseSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_report_entry_snapshot(
    List<ReportEntrySnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_required_expense_snapshot(
    List<RequiredExpenseSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_planned_report_snapshot(
    PlannedReportSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_planned_snapshot(
    PlannedSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_preferences_snapshot(
    PreferencesSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_purchase_snapshot(
    PurchaseSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_report_entry_snapshot(
    ReportEntrySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_report_snapshot(
    ReportSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_required_expense_snapshot(
    RequiredExpenseSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchAppPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pouch_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchAppPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchAppPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pouch_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchApp =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPouchAppPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
